### ISSUE TITLE
Bold font and other text formating

### ISSUE THREAD

**Issue by lbertolotti** [miraisolutions/xlconnect#64] opened 2017-02-02 13:17 UTC
XLConnect Version 0.2-12 June, 2016:
https://cran.r-project.org/web/packages/XLConnect/vignettes/XLConnect.pdf
```
library(XLConnect)
w <- loadWorkbook("Template.xlsx")
df <- data.frame("foo")
c <- getCellStyle(w, "FatFont")

writeWorksheet(w, data=df , sheet=1,startRow=1,startCo
               l=1,header=TRUE)
setCellStyle(w, sheet=1,row=1,col=1,cellstyle=c)
saveWorkbook(w)
```
Output:
```
> library(XLConnect)
> w <- loadWorkbook("Template.xlsx")
> df <- data.frame("foo")
> c <- getCellStyle(w, "FatFont")
Error: IllegalArgumentException (Java): Cell style FatFont does not exist
> 
> writeWorksheet(w, data=df , sheet=1,startRow=1,startCo
+                l=1,header=TRUE)
Error: unexpected symbol in:
"writeWorksheet(w, data=df , sheet=1,startRow=1,startCo
               l"
> setCellStyle(w, sheet=1,row=1,col=1,cellstyle=c)
Error in FUN(X[[i]], ...) : 
  Sorry, parameter type `NA' is ambiguous or not supported.
> saveWorkbook(w)
```
Is this still supported?

**Comment by martinstuder** [comment] 2017-02-21 13:57
Are you sure the there actually is a cell style called "FatFont" in your template? If so, could you upload the template file such that we can try to reproduce the issue on our end?

**Comment by martinstuder** [comment] 2018-04-05 05:44
Closing since no reproducible example is available.

**Closed by martinstuder** 2018-04-05 05:44 UTC
