### ISSUE TITLE
Error when connecting the XL Connect package(It seems downloading the JAR dependencies may have failed)

### ISSUE THREAD

**Issue by MindFure** [miraisolutions/xlconnect#138] opened 2021-05-13 04:22 UTC
Hi, I get an error when I try to connect xlconnect , I can't understand why this happens, I downloaded the xlconnect jars package separately, but it didn't help.

```
XLConnect: It seems downloading the JAR dependencies may have failed. If you would like to use a different maven repository, please set the environment variable XLCONNECT_JAVA_REPO_URL to a valid URL, e.g. Sys.setenv(XLCONNECT_JAVA_REPO_URL='https://jcenter.bintray.com'), and reinstall the package.
XLConnect 1.0.2 by Mirai Solutions GmbH [aut],
  Martin Studer [cre],
  The Apache Software Foundation [ctb, cph] (Apache POI),
  Graph Builder [ctb, cph] (Curvesapi Java library)
https://mirai-solutions.ch
https://github.com/miraisolutions/xlconnect
```

**Comment by spoltier** [comment] 2021-05-18 09:43
Duplicate of #122 - XLConnectJars is no longer needed since 1.0. See also #132.

**Closed by spoltier** 2021-05-18 09:43 UTC
